version: '{build}'
image: 
  - Ubuntu
  - Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
build_script:
- ps: .\build.ps1
- sh: ./build.sh
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet

for:
-
  matrix:
    only:
      - image: Ubuntu

  deploy:
  - provider: NuGet
    server: https://www.myget.org/F/andrewlock-ci/api/v2/package
    api_key:
      secure: 7XbdNq38u0JLRNc9pRl35WPi5LZopfYcoCslf7Er/eTreR5mZnGbmY/lVQYcgxI2
    skip_symbols: true
    on:
      branch: master
  - provider: NuGet
    name: production
    api_key:
      secure: nyE3SEqDxSkHrLGAQJBMh2Oo6deEnWCEKoHCVafYuUB7NwjOUwDi3jXQItElcp2h
    on:
      branch: master
      appveyor_repo_tag: true